# Generated by Django 5.0.7 on 2024-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room', max_length=255),
            preserve_default=False,
        ),
    ]
