# Generated by Django 5.0.7 on 2024-08-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0002_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomaccount',
            name='session_key',
        ),
    ]
