# Generated by Django 5.0.7 on 2024-08-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayo', '0003_remove_roomaccount_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='menu',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='aayo.cafe')),
            ],
        ),
    ]
